//! Phase 5 API substrate.
//!
//! This crate is intentionally outside the trusted kernel. It handles wire JSON
//! decoding and request-shape validation for machine-facing endpoints.
//! Phase 4/5/7 candidate APIs operate on `MachineTacticCandidate`; Phase 2
//! producer fast-path candidates remain in `npa-cert` until a separate upper-crate
//! bridge is designed.
//!
//! ```compile_fail
//! use npa_api::phase7_candidate_payload_hash;
//! use npa_cert::CoreDeclCandidate;
//!
//! let candidate: &CoreDeclCandidate = unimplemented!();
//! let _ = phase7_candidate_payload_hash(candidate);
//! ```

mod adapter;
mod callable;
mod current;
mod diagnostic;
mod json;
mod phase7;
mod phase8;
mod phase9;
mod projection;
mod prompt;
mod renderer;
mod replay;
mod search;
mod session;
mod snapshot;
mod std_library;
mod tactic;
mod types;
mod validation;
mod verify;

pub use adapter::{
    map_phase3_diagnostic_kind, map_phase4_diagnostic_kind,
    phase4_extract_closed_machine_theorem_decl, phase4_machine_tactic_result_error,
    phase4_run_machine_tactic, phase4_run_machine_tactic_with_budget, phase4_start_machine_proof,
    phase4_validate_machine_tactic_candidate, MachineApiDiagnosticPhase,
    MachineApiDiagnosticProjection, MachineApiTacticKind, Phase4AdapterError, Phase4AdapterResult,
    Phase4ExtractedTheorem, Phase4StartProofOutput, Phase4TacticRunOutput, Phase4ValidatedTactic,
    Phase5UpstreamDiagnostic,
};
pub use callable::{
    build_machine_surface_callable_interface_table,
    build_machine_surface_callable_interface_table_from_parts,
    MachineSurfaceCallableInterfaceBuildError,
};
pub use current::{
    project_checked_current_decl_context, project_checked_current_decl_context_with_kernel_profile,
    CheckedCurrentDeclPackageInput, CheckedCurrentDeclProjectionError, CurrentDeclDependencyEntry,
    CurrentDeclDependencyReport, CurrentDeclIndexEntry, CurrentGeneratedDeclEntry,
    CurrentGeneratedDeclKind, MachineAxiomRefWire, MachineCheckedCurrentDeclContext,
    MachineCheckedDeclSignature, MachineDependencyRefWire,
};
pub use diagnostic::{
    machine_api_diagnostic_canonical_bytes, machine_api_diagnostic_hash,
    MachineApiDiagnosticCanonicalizationError,
};
pub use json::{
    JsonDocument, JsonMember, JsonParseError, JsonParseErrorKind, JsonParseLimits, JsonSpan,
    JsonValue, JsonValueKind,
};
pub use phase7::{
    filter_phase7_candidate_envelopes, load_phase7_initial_snapshot,
    parse_phase7_mvp_controller_config, phase7_assign_candidate_ids, phase7_build_replay_plan,
    phase7_builtin_candidate_envelopes, phase7_candidate_cost_estimate, phase7_candidate_envelope,
    phase7_candidate_forbidden_token, phase7_candidate_hash_mismatch,
    phase7_candidate_payload_hash, phase7_candidate_payload_json, phase7_cap_batch_policy,
    phase7_evaluate_tactic_batch_response, phase7_expected_effect, phase7_fresh_intro_name,
    phase7_goal_summaries, phase7_minimize_replay_plan, phase7_mvp_candidate_envelopes,
    phase7_mvp_candidate_generation, phase7_mvp_premise_query_json,
    phase7_negative_training_identity, phase7_negative_training_identity_hash,
    phase7_negative_training_identity_json, phase7_positive_training_identity,
    phase7_positive_training_identity_hash, phase7_positive_training_identity_json,
    phase7_premise_cache_entries, phase7_premise_retrieval_from_search_ok, phase7_premise_usages,
    phase7_rank_and_dedupe_candidate_envelopes, phase7_rank_filter_and_dedupe_candidate_envelopes,
    phase7_repair_depth_of, phase7_replay_plan_json, phase7_replay_request_json,
    phase7_replay_step_json, phase7_retrieval_cache_key, phase7_rule_based_repair_action,
    phase7_run_mvp_search, phase7_run_tactic_batch, phase7_search_node_best_partial_key,
    phase7_search_node_priority_key, phase7_snapshot_get_request_json,
    phase7_suggested_candidate_envelopes, phase7_tactic_batch_request_json,
    phase7_training_trace_record_json, phase7_training_trace_records_json,
    phase7_verify_request_json, retrieve_phase7_premises, select_phase7_goal,
    validate_phase7_mvp_controller_config, Phase7AcceptedCandidateFailure,
    Phase7AcceptedCandidateFailureRecord, Phase7AssignedCandidate, Phase7BatchEvaluation,
    Phase7BestPartialKey, Phase7BuiltinKind, Phase7CandidateCostEstimate, Phase7CandidateCostRisk,
    Phase7CandidateEnvelope, Phase7CandidateFilterError, Phase7CandidateFilterResult,
    Phase7CandidateMetadata, Phase7CandidateRankMetadata, Phase7CandidateRepairMetadata,
    Phase7CandidateSource, Phase7DeferredCandidate, Phase7DeferredCandidateDropReason,
    Phase7ExpectedEffect, Phase7FakeMachineApiClient, Phase7ForbiddenToken,
    Phase7ForbiddenTokenClass, Phase7GoalSummary, Phase7InitialSnapshot,
    Phase7LocalMachineApiClient, Phase7MachineApiCall, Phase7MachineApiClient,
    Phase7MachineApiEndpointKind, Phase7MachineApiError, Phase7MachineApiResult,
    Phase7MachineControllerError, Phase7MachineControllerErrorKind, Phase7MachineControllerResult,
    Phase7MinimizationResult, Phase7MinimizationStats, Phase7MvpControllerConfig,
    Phase7NegativeTrainingIdentity, Phase7NodeId, Phase7NodeStatus,
    Phase7NonAcceptedCandidateError, Phase7PendingCandidate, Phase7PositiveTrainingIdentity,
    Phase7PremiseCacheEntry, Phase7PremiseQueryRequest, Phase7PremiseRef, Phase7PremiseRetrieval,
    Phase7PremiseUsage, Phase7RejectedCandidateEnvelope, Phase7RepairCandidateOutput,
    Phase7RepairChainStopReason, Phase7ReplayPlan, Phase7ReplayStep, Phase7ReplayStepEdit,
    Phase7RetrievalCacheKey, Phase7RuleBasedRepair, Phase7RuleBasedRepairAction,
    Phase7SchedulerStop, Phase7Score, Phase7SearchBudget, Phase7SearchBudgetLimit,
    Phase7SearchFailure, Phase7SearchFailureReason, Phase7SearchInput, Phase7SearchNode,
    Phase7SearchPriorityKey, Phase7SearchResult, Phase7SearchStats, Phase7SearchTraceEvent,
    Phase7SearchTraceEventKind, Phase7SnapshotGetRequest, Phase7SuccessfulCandidateTransition,
    Phase7TacticBatchRequest, Phase7TacticBatchRunError, Phase7TraceEvent,
    Phase7TrainingTraceCandidate, Phase7TrainingTraceRecord, Phase7TrustFlags, Phase7VerifiedProof,
    PHASE7_TRAINING_TRACE_SCHEMA,
};
pub use phase8::{
    evaluate_required_ai_sidecar_diagnostics, parse_phase8_ai_audit_input_policy,
    parse_phase8_ai_audit_sidecar, parse_phase8_auxiliary_result,
    parse_phase8_auxiliary_result_store_manifest, parse_phase8_axiom_policy_toml,
    parse_phase8_axiom_report, parse_phase8_axiom_report_store_manifest,
    parse_phase8_challenge_coverage_summary, parse_phase8_challenge_generation_request,
    parse_phase8_challenge_manifest, parse_phase8_challenge_output_store_manifest,
    parse_phase8_challenge_replay_result, parse_phase8_challenge_replay_store_manifest,
    parse_phase8_checker_binary_registry, parse_phase8_checker_identity_manifest,
    parse_phase8_checker_raw_result, parse_phase8_import_lock_manifest,
    parse_phase8_machine_check_request, parse_phase8_machine_result_store_manifest,
    parse_phase8_machine_result_store_reference, parse_phase8_normalized_result_store_manifest,
    parse_phase8_release_audit_bundle_manifest, parse_phase8_release_bundle_staging_plan,
    parse_phase8_release_policy, parse_phase8_request_store_manifest,
    parse_phase8_request_store_reference, parse_phase8_runner_policy,
    parse_phase8_runner_policy_reference, phase8_ai_audit_input_policy_hash,
    phase8_ai_audit_prompt_input_for_sidecar,
    phase8_ai_sidecar_diagnostic_targets_from_normalized_result,
    phase8_auxiliary_axiom_policy_result, phase8_auxiliary_axiom_policy_result_with_selector,
    phase8_auxiliary_command_exit_success, phase8_auxiliary_import_certificate_hash_result,
    phase8_auxiliary_output_write_failure, phase8_auxiliary_reproducibility_result,
    phase8_auxiliary_reproducibility_result_with_selector,
    phase8_auxiliary_result_passes_release_condition,
    phase8_auxiliary_result_store_entry_for_result, phase8_auxiliary_result_store_with_entry,
    phase8_auxiliary_results_all_passed, phase8_build_normalized_comparison,
    phase8_canonical_json_bytes, phase8_canonical_json_object_excluding_top_level_fields,
    phase8_canonical_json_string, phase8_canonical_json_value_bytes,
    phase8_challenge_coverage_summary, phase8_challenge_coverage_summary_hash,
    phase8_challenge_generate, phase8_challenge_generation_request_hash,
    phase8_challenge_manifest_expected_certificate_hash,
    phase8_challenge_manifest_is_rejection_required, phase8_challenge_materialize_requests,
    phase8_challenge_output_store_with_entry, phase8_challenge_replay_aggregate,
    phase8_challenge_replay_result_hash, phase8_challenge_replay_store_entry_for_result,
    phase8_challenge_replay_store_with_entry, phase8_checker_argv,
    phase8_compare_normalized_result, phase8_file_hash,
    phase8_first_forbidden_verification_input_field, phase8_forbids_verification_input_field,
    phase8_hash_json_object_excluding_top_level_fields, phase8_hash_usage_rule,
    phase8_json_artifact_hash_from_source, phase8_machine_check_request_hash,
    phase8_machine_check_run, phase8_machine_result_store_entry_for_result,
    phase8_machine_result_store_with_entry, phase8_normalization_write_result,
    phase8_normalize_results, phase8_normalized_result_store_entry_for_result,
    phase8_normalized_result_store_with_entry, phase8_raw_certificate_claims,
    phase8_raw_claimed_certificate_hash, phase8_release_bundle, phase8_release_policy_hash,
    phase8_release_stage_bundle_inputs,
    phase8_release_target_has_required_ai_sidecar_diagnostic_targets,
    phase8_release_validate_bundle, phase8_request_materialize,
    phase8_request_store_with_materialized_entry, phase8_required_ai_sidecar_diagnostic_targets,
    phase8_resolve_checker_executable, phase8_rfc8785_object_key_cmp,
    phase8_runner_fixed_environment, phase8_runner_policy_hash, phase8_sha256,
    phase8_training_export, phase8_validate_ai_audit_sidecar_cross_artifact,
    phase8_validate_ai_audit_sidecar_schema_only, phase8_validate_release_policy_runner_trust,
    phase8_validate_selected_checker_identity_manifest, validate_phase8_closed_object,
    Phase8AiAuditInputPolicy, Phase8AiAuditPromptInput, Phase8AiAuditSidecar,
    Phase8AiAuditSidecarAi, Phase8AiAuditSidecarClassification, Phase8AiAuditSidecarInputPolicy,
    Phase8AiAuditSidecarSource, Phase8AiAuditSidecarSourceKind, Phase8AiAuditSidecarStatus,
    Phase8AiSidecarDiagnosticError, Phase8AiSidecarDiagnosticEvaluationFailure,
    Phase8AiSidecarDiagnosticEvaluationFailureReasonCode,
    Phase8AiSidecarDiagnosticFailureReasonCode, Phase8AiSidecarDiagnosticPassFailure,
    Phase8AiSidecarDiagnosticPassFailureReasonCode, Phase8AiSidecarDiagnosticResult,
    Phase8AiSidecarDiagnosticStatus, Phase8ApiError, Phase8ApiErrorReasonCode,
    Phase8ArtifactClassification, Phase8ArtifactKind, Phase8ArtifactSelector,
    Phase8AuditSidecarValidationError, Phase8AuditSidecarValidationMode,
    Phase8AuditSidecarValidationReasonCode, Phase8AuditSidecarValidationResult,
    Phase8AuditSidecarValidationStatus, Phase8AuxiliaryError, Phase8AuxiliaryReasonCode,
    Phase8AuxiliaryResult, Phase8AuxiliaryResultKind, Phase8AuxiliaryResultStoreEntry,
    Phase8AuxiliaryResultStoreManifest, Phase8AuxiliaryResultStoreUpdate, Phase8AuxiliarySelector,
    Phase8AuxiliaryStatus, Phase8AxiomPolicy, Phase8AxiomReport, Phase8AxiomReportEntry,
    Phase8AxiomReportStoreEntry, Phase8AxiomReportStoreManifest, Phase8CanonicalJsonError,
    Phase8ChallengeBaseCertificate, Phase8ChallengeCoverageEntry, Phase8ChallengeCoverageSummary,
    Phase8ChallengeGeneratedBy, Phase8ChallengeGeneratedByKind,
    Phase8ChallengeGeneratedCertificate, Phase8ChallengeGeneration,
    Phase8ChallengeGenerationOutput, Phase8ChallengeGenerationRequest,
    Phase8ChallengeGenerationResult, Phase8ChallengeImports, Phase8ChallengeManifest,
    Phase8ChallengeManifestReference, Phase8ChallengeMaterializedRequestEntry,
    Phase8ChallengeMutatedCertificate, Phase8ChallengeMutation, Phase8ChallengeMutationKind,
    Phase8ChallengeOutcomeHint, Phase8ChallengeOutputStoreEntry,
    Phase8ChallengeOutputStoreManifest, Phase8ChallengeOutputStoreReference,
    Phase8ChallengeOutputStoreUpdate, Phase8ChallengeReplayAggregation,
    Phase8ChallengeReplayCheckerResult, Phase8ChallengeReplayMetadata, Phase8ChallengeReplayResult,
    Phase8ChallengeReplayStoreEntry, Phase8ChallengeReplayStoreManifest,
    Phase8ChallengeReplayStoreUpdate, Phase8ChallengeRequestMaterialization,
    Phase8ChallengeRequestMaterializationResult, Phase8CheckerAllowlistEntry,
    Phase8CheckerBinaryRegistry, Phase8CheckerBinaryRegistryEntry,
    Phase8CheckerBinaryRegistryRootKind, Phase8CheckerIdentityEntry,
    Phase8CheckerIdentityGeneratedBy, Phase8CheckerIdentityManifest,
    Phase8CheckerIdentityManifestReference, Phase8CheckerRawResult, Phase8CheckerRunObservation,
    Phase8CiDiagnosticTargetContext, Phase8ClosedSchema, Phase8CommandError, Phase8CommandName,
    Phase8CompareValidationError, Phase8CompareValidationErrorKind, Phase8CompareValidationResult,
    Phase8CompareValidationStatus, Phase8FieldSpec, Phase8HashInputKind, Phase8HashUsageKind,
    Phase8HashUsageRule, Phase8ImportLockCertificate, Phase8ImportLockEntry,
    Phase8ImportLockManifest, Phase8JsonFieldType, Phase8JsonPath, Phase8JsonPathElement,
    Phase8MachineCheckChecker, Phase8MachineCheckError, Phase8MachineCheckProcess,
    Phase8MachineCheckRequest, Phase8MachineCheckRequestCertificate,
    Phase8MachineCheckRequestErrorReasonCode, Phase8MachineCheckRequestErrorResult,
    Phase8MachineCheckRequestImports, Phase8MachineCheckRequestPolicy,
    Phase8MachineCheckResourceUsage, Phase8MachineCheckResult, Phase8MachineCheckRunner,
    Phase8MachineCheckStatus, Phase8MachineResultStoreEntry, Phase8MachineResultStoreManifest,
    Phase8MachineResultStoreReference, Phase8MachineResultStoreUpdate,
    Phase8NormalizationWriteResult, Phase8NormalizationWriteStore, Phase8NormalizeErrorReasonCode,
    Phase8NormalizeErrorResult, Phase8NormalizedArtifact, Phase8NormalizedCheckResult,
    Phase8NormalizedCheckResultEntry, Phase8NormalizedComparison, Phase8NormalizedComparisonStatus,
    Phase8NormalizedDisagreement, Phase8NormalizedFailureKey, Phase8NormalizedResultStoreEntry,
    Phase8NormalizedResultStoreManifest, Phase8NormalizedResultStoreUpdate,
    Phase8NormalizedStatusReason, Phase8PipelineErrorKind, Phase8PolicyFailure,
    Phase8PolicyFailureReasonCode, Phase8PolicyValidationError, Phase8RawCertificateClaims,
    Phase8RawResultSchemaError, Phase8ReleaseAuditBundleArtifact, Phase8ReleaseAuditBundleManifest,
    Phase8ReleaseBundleArtifactKind, Phase8ReleaseBundleGeneration,
    Phase8ReleaseBundleStagedArtifact, Phase8ReleaseBundleStagedFile,
    Phase8ReleaseBundleStagedStoreManifest, Phase8ReleaseBundleStaging,
    Phase8ReleaseBundleStagingInput, Phase8ReleaseBundleStagingPhase,
    Phase8ReleaseBundleStagingPlan, Phase8ReleaseBundleStagingResult,
    Phase8ReleaseBundleValidation, Phase8ReleaseMode, Phase8ReleasePolicy,
    Phase8ReleasePolicyAiTriage, Phase8RequestMaterialization, Phase8RequestStoreEntry,
    Phase8RequestStoreManifest, Phase8RequestStoreReference, Phase8RequestStoreUpdate,
    Phase8RequestValidationError, Phase8RequiredAiSidecarDiagnosticEvaluation,
    Phase8RequiredAiSidecarDiagnosticTarget, Phase8RequiredAiSidecarDiagnosticTargetKind,
    Phase8ResolvedAiAuditSidecarEntry, Phase8ResolvedAiSidecarDiagnosticResultEntry,
    Phase8ResolvedAuditSidecarValidationEntry, Phase8ResolvedCheckerExecutable,
    Phase8RunnerAxiomPolicy, Phase8RunnerBudget, Phase8RunnerDynamicArgs, Phase8RunnerImportPolicy,
    Phase8RunnerPolicy, Phase8RunnerPolicyReference, Phase8SchemaError, Phase8SchemaErrorReason,
    Phase8StoredMachineCheckRequest, Phase8StructuredError, Phase8TrainingExample,
    Phase8TrainingExampleIdentity, Phase8TrainingExampleInput, Phase8TrainingExampleLabel,
    Phase8TrainingExampleSource, Phase8TrainingExport, Phase8TrainingExportManifest,
    Phase8TrainingExportSources, Phase8TrustMode, Phase8ValidatedObject,
    PHASE8_AI_AUDIT_INPUT_POLICY_SCHEMA, PHASE8_AI_AUDIT_PROMPT_INPUT_SCHEMA,
    PHASE8_AI_AUDIT_SIDECAR_SCHEMA, PHASE8_AI_SIDECAR_DIAGNOSTIC_EVALUATION_FAILURE_SCHEMA,
    PHASE8_AI_SIDECAR_DIAGNOSTIC_RESULT_SCHEMA, PHASE8_API_ERROR_SCHEMA,
    PHASE8_AUDIT_SIDECAR_VALIDATION_RESULT_SCHEMA, PHASE8_AUXILIARY_RESULT_SCHEMA,
    PHASE8_AUXILIARY_RESULT_STORE_MANIFEST_SCHEMA, PHASE8_AXIOM_POLICY_TOML_FORMAT,
    PHASE8_AXIOM_REPORT_SCHEMA, PHASE8_AXIOM_REPORT_STORE_MANIFEST_SCHEMA,
    PHASE8_CHALLENGE_COVERAGE_SUMMARY_SCHEMA, PHASE8_CHALLENGE_GENERATION_REQUEST_SCHEMA,
    PHASE8_CHALLENGE_GENERATION_RESULT_SCHEMA, PHASE8_CHALLENGE_MANIFEST_SCHEMA,
    PHASE8_CHALLENGE_OUTPUT_STORE_MANIFEST_SCHEMA, PHASE8_CHALLENGE_REPLAY_RESULT_SCHEMA,
    PHASE8_CHALLENGE_REPLAY_STORE_MANIFEST_SCHEMA,
    PHASE8_CHALLENGE_REQUEST_MATERIALIZATION_RESULT_SCHEMA, PHASE8_CHECKER_BINARY_REGISTRY_SCHEMA,
    PHASE8_CHECKER_IDENTITY_MANIFEST_SCHEMA, PHASE8_CHECKER_RAW_RESULT_SCHEMA,
    PHASE8_COMMAND_ERROR_SCHEMA, PHASE8_COMPARE_VALIDATION_RESULT_SCHEMA,
    PHASE8_FORBIDDEN_VERIFICATION_INPUT_FIELDS, PHASE8_IMPORT_LOCK_MANIFEST_SCHEMA,
    PHASE8_MACHINE_CHECK_REQUEST_ERROR_RESULT_SCHEMA, PHASE8_MACHINE_CHECK_REQUEST_SCHEMA,
    PHASE8_MACHINE_CHECK_RESULT_SCHEMA, PHASE8_MACHINE_RESULT_STORE_MANIFEST_SCHEMA,
    PHASE8_NORMALIZATION_WRITE_RESULT_SCHEMA, PHASE8_NORMALIZED_CHECK_RESULT_SCHEMA,
    PHASE8_NORMALIZED_RESULT_STORE_MANIFEST_SCHEMA, PHASE8_NORMALIZE_ERROR_RESULT_SCHEMA,
    PHASE8_RELEASE_AUDIT_BUNDLE_MANIFEST_SCHEMA, PHASE8_RELEASE_BUNDLE_STAGING_PLAN_SCHEMA,
    PHASE8_RELEASE_BUNDLE_STAGING_RESULT_SCHEMA, PHASE8_RELEASE_POLICY_SCHEMA,
    PHASE8_REQUEST_STORE_MANIFEST_SCHEMA, PHASE8_RUNNER_DYNAMIC_FLAGS,
    PHASE8_RUNNER_FIXED_ENVIRONMENT, PHASE8_RUNNER_POLICY_SCHEMA, PHASE8_TRAINING_EXAMPLE_SCHEMA,
    PHASE8_TRAINING_EXPORT_MANIFEST_SCHEMA,
};
pub use phase9::{
    phase9_ai_candidate_envelope_canonical_bytes, phase9_ai_candidate_hash,
    phase9_ai_env_fingerprint, phase9_ai_goal_canonical_bytes, phase9_ai_goal_fingerprint,
    phase9_ai_options_canonical_bytes, phase9_ai_options_hash,
    phase9_ai_validation_result_hash_for_rejection, phase9_ai_validation_result_hash_for_success,
    phase9_file_hash, phase9_formalization_accepted_statement_hash,
    phase9_formalization_candidate_statement_hash, phase9_formalization_claim_span_hash,
    phase9_formalization_payload_canonical_bytes, phase9_formalization_proof_root_hash,
    phase9_formalization_rejection_reason_hash, phase9_formalization_source_document_hash,
    phase9_inductive_proposal_canonical_bytes, phase9_quotient_candidate_canonical_bytes,
    phase9_smt_candidate_canonical_bytes, phase9_smt_command_id, phase9_smt_encoding_hash,
    phase9_smt_problem_canonical_bytes, phase9_smt_problem_hash,
    phase9_smt_proof_payload_canonical_bytes, phase9_smt_proof_payload_hash,
    phase9_smt_symbol_canonical_bytes, phase9_theorem_graph_query_canonical_bytes,
    phase9_theorem_graph_query_features_canonical_bytes, phase9_theorem_graph_query_features_hash,
    phase9_theorem_graph_snapshot_canonical_bytes, phase9_theorem_graph_snapshot_hash,
    phase9_typeclass_resolution_plan_canonical_bytes,
    phase9_universe_repair_candidate_canonical_bytes, run_phase9_formalize_check_request,
    run_phase9_inductive_check_request, run_phase9_quotient_check_request,
    run_phase9_smt_reconstruct_request, run_phase9_theorem_graph_query_request,
    run_phase9_typeclass_resolve_request, run_phase9_universe_repair_check_request,
    validate_phase9_ai_common_envelope, Phase9AdvancedInductiveError,
    Phase9AdvancedInductiveOptions, Phase9AiCandidateEnvelope, Phase9AiCanonicalError,
    Phase9AiEndpointError, Phase9AiEndpointResponse, Phase9AiFeatureError, Phase9AiGlobalRef,
    Phase9AiGoal, Phase9AiOptions, Phase9AiOptionsRef, Phase9AiOptionsVersion,
    Phase9AiProfileVersion, Phase9AiSuccessPayload, Phase9AiTarget, Phase9AiTaskKind,
    Phase9AiValidationError, Phase9FormalizationError, Phase9FormalizationIntentRecord,
    Phase9FormalizationIntentStatus, Phase9FormalizationOptions, Phase9FormalizationSuccessKind,
    Phase9ImportIdentity, Phase9IndependentCheckerOptions, Phase9IndependentCheckerProfile,
    Phase9MachineConstructorProposal, Phase9MachineExprOccurrence, Phase9MachineExprPathStep,
    Phase9MachineFormalizationCandidate, Phase9MachineFormalizationCheckPayload,
    Phase9MachineFormalizationClaimSpan, Phase9MachineFormalizationProofCandidate,
    Phase9MachineFormalizationRejectionReasonRef, Phase9MachineFormalizationSourceDocumentRef,
    Phase9MachineInductiveFamilyProposal, Phase9MachineInductiveProposal,
    Phase9MachineInstanceCandidateRef, Phase9MachineInstanceTargetRef,
    Phase9MachineQuotientConstructionCandidate, Phase9MachineQuotientOperationCandidate,
    Phase9MachineSmtCertificateCandidate, Phase9MachineSmtEncodedProblem,
    Phase9MachineSmtPayloadBinding, Phase9MachineSmtProblemRef, Phase9MachineSmtProofPayloadRef,
    Phase9MachineSmtReconstructionPlan, Phase9MachineSmtReconstructionStep,
    Phase9MachineSurfaceTerm, Phase9MachineTelescopeBinder, Phase9MachineTheoremGraphEdge,
    Phase9MachineTheoremGraphFeature, Phase9MachineTheoremGraphNodeRef,
    Phase9MachineTheoremGraphQuery, Phase9MachineTheoremGraphQueryFeatures,
    Phase9MachineTheoremGraphQueryFeaturesRef, Phase9MachineTheoremGraphResult,
    Phase9MachineTheoremGraphResultEntry, Phase9MachineTheoremGraphScore,
    Phase9MachineTheoremGraphSnapshot, Phase9MachineTheoremGraphSnapshotRef,
    Phase9MachineTheoremGraphSnapshotSource, Phase9MachineTypeclassResolutionPlan,
    Phase9QuotientConstructionError, Phase9QuotientOptions, Phase9ReviewerId, Phase9SmtBuiltinOp,
    Phase9SmtCertificateError, Phase9SmtCertificateFormat, Phase9SmtCommandPayload,
    Phase9SmtCommandPhase, Phase9SmtCommandProfile, Phase9SmtConclusionEncoding,
    Phase9SmtDatatypeConstructor, Phase9SmtDatatypeSelector, Phase9SmtEncodedCommand,
    Phase9SmtEncoderVersion, Phase9SmtExpr, Phase9SmtLocalBookkeepingRule, Phase9SmtLogic,
    Phase9SmtOptions, Phase9SmtProofNode, Phase9SmtProofNodeTable, Phase9SmtReconstructionRule,
    Phase9SmtRuleRegistryProfile, Phase9SmtSortExpr, Phase9SmtSymbol, Phase9TheoremGraphEdgeKind,
    Phase9TheoremGraphError, Phase9TheoremGraphExtractorVersion, Phase9TheoremGraphFeatureKey,
    Phase9TheoremGraphFeatureSchemaVersion, Phase9TheoremGraphFeatureValue,
    Phase9TheoremGraphRankingProfile, Phase9TypeclassOptions, Phase9TypeclassResolutionError,
    Phase9UniverseConstraint, Phase9UniverseConstraintHint, Phase9UniverseConstraintHintReason,
    Phase9UniverseConstraintRelation, Phase9UniverseInstantiationPatch,
    Phase9UniverseMinimizationHint, Phase9UniverseRepairCandidate, Phase9UniverseRepairError,
    Phase9ValidatedCommonEnvelope, PHASE9_FORMALIZE_CHECK_ENDPOINT,
    PHASE9_INDUCTIVE_CHECK_ENDPOINT, PHASE9_QUOTIENT_CHECK_ENDPOINT,
    PHASE9_SMT_RECONSTRUCT_ENDPOINT, PHASE9_THEOREM_GRAPH_QUERY_ENDPOINT,
    PHASE9_TYPECLASS_RESOLVE_ENDPOINT, PHASE9_UNIVERSE_REPAIR_CHECK_ENDPOINT,
};
pub use projection::{
    project_import_certificate_context, GeneratedDeclKind, ImportProjectionError,
    MachineImportCertificateContext, VerifiedImportDeclIndexEntry,
    VerifiedImportGeneratedDeclEntry, VerifiedImportGeneratedDeclPayload, VerifiedImportKey,
    VerifiedModuleCertificateInput, VerifiedModuleContextEntry,
};
pub use prompt::{
    build_machine_prompt_payload, build_machine_prompt_payload_in_sessions,
    parse_machine_prompt_payload_request, FailedCandidateErrorKind, FailedCandidatePromptItem,
    MachinePromptGoal, MachinePromptLocal, MachinePromptPayloadError, MachinePromptPayloadOkFields,
    MachinePromptPayloadRequest, MachinePromptPayloadResponse, MachinePromptPremise,
    MachinePromptPremiseSelection,
};
pub use renderer::{
    render_machine_expr_source, render_machine_expr_view, renderer_qa_round_trip, LocalId,
    MachineDisplayRenderScope, MachineDisplayRenderScopeEntry, MachineExprRendererContext,
    MachineExprRendererError, MachineExprView, MachineGlobalRefView,
    Phase5ResolvedDisplayCoreRefOwner,
};
pub use replay::{
    parse_machine_replay_request, run_machine_replay_request,
    run_machine_replay_request_in_sessions, MachineReplayError, MachineReplayOkFields,
    MachineReplayPlan, MachineReplayRequest, MachineReplayResponse, MachineReplayStep,
};
pub use search::{
    parse_machine_theorem_search_request, search_machine_theorems_for_goal,
    search_machine_theorems_for_goal_in_sessions, MachineAllowedModulesFilter,
    MachineSuggestedCandidate, MachineSuggestedCandidateStatus, MachineTheoremFilters,
    MachineTheoremGlobalRef, MachineTheoremMode, MachineTheoremSearchError,
    MachineTheoremSearchOkFields, MachineTheoremSearchRequest, MachineTheoremSearchResponse,
    MachineTheoremSearchResult, MachineTheoremStatement,
};
pub use session::{
    create_machine_session, MachineSessionCreateError, MachineSessionCreateOk,
    MachineSessionCreateRequest,
};
pub use snapshot::{
    get_machine_snapshot, get_machine_snapshot_from_session, materialize_machine_proof_snapshot,
    parse_machine_snapshot_get_request, stored_snapshot_view_canonical_bytes,
    MachineSnapshotGetError, MachineSnapshotGetOk, MachineSnapshotGetRequest,
    MachineSnapshotLookupError, MachineSnapshotMaterializationContext,
    MachineSnapshotMaterializationError, MachineSnapshotStore, MachineSnapshotStoreError,
    StoredSnapshotEntry, StoredSnapshotView,
};
pub use std_library::{
    audit_machine_std_mvp_release_artifacts, audit_machine_std_mvp_validated_release,
    finalize_machine_std_mvp_import_bundle_recipes, finalize_machine_std_mvp_theorem_index,
    generate_machine_std_mvp_final_import_bundle_set, generate_machine_std_mvp_final_theorem_index,
    generate_machine_std_mvp_import_bundle_set, generate_machine_std_mvp_rewrite_profile_set,
    generate_machine_std_mvp_simp_profile_set, generate_machine_std_mvp_theorem_index,
    load_machine_std_certificates_from_locators, load_machine_std_mvp_certificates,
    load_machine_std_mvp_release,
    load_machine_std_mvp_release_with_optional_prompt_metadata_from_json,
    load_machine_std_mvp_release_with_sidecars_from_json, machine_std_audit_check_canonical_bytes,
    machine_std_audit_report_canonical_bytes, machine_std_audit_report_hash,
    machine_std_axiom_ref_canonical_bytes, machine_std_axiom_report_canonical_bytes,
    machine_std_axiom_report_hash, machine_std_global_ref_canonical_bytes,
    machine_std_global_ref_view_canonical_bytes, machine_std_import_bundle_canonical_bytes,
    machine_std_import_bundle_hash, machine_std_import_bundle_set_canonical_bytes,
    machine_std_import_bundle_set_hash, machine_std_library_release_canonical_bytes,
    machine_std_library_release_hash, machine_std_module_artifact_canonical_bytes,
    machine_std_mvp_module_locators, machine_std_prompt_example_canonical_bytes,
    machine_std_prompt_metadata_canonical_bytes, machine_std_prompt_metadata_hash,
    machine_std_prompt_metadata_set_canonical_bytes,
    machine_std_rewrite_descriptor_canonical_bytes, machine_std_rewrite_profile_canonical_bytes,
    machine_std_rewrite_profile_hash, machine_std_rewrite_profile_set_canonical_bytes,
    machine_std_rewrite_profile_set_hash, machine_std_rule_telescope_canonical_bytes,
    machine_std_rule_telescope_hash, machine_std_simp_profile_canonical_bytes,
    machine_std_simp_profile_hash, machine_std_simp_profile_set_canonical_bytes,
    machine_std_simp_profile_set_hash, machine_std_tactic_options_recipe_canonical_bytes,
    machine_std_tactic_options_recipe_request, machine_std_theorem_entry_canonical_bytes,
    machine_std_theorem_index_canonical_bytes, machine_std_theorem_index_hash,
    parse_machine_std_axiom_report_json, parse_machine_std_import_bundle_set_json,
    parse_machine_std_library_release_json, parse_machine_std_prompt_metadata_json,
    parse_machine_std_rewrite_profile_set_json, parse_machine_std_simp_profile_set_json,
    parse_machine_std_theorem_index_json, validate_machine_std_locator_path,
    validate_machine_std_mvp_final_theorem_index, validate_machine_std_mvp_import_bundle_recipes,
    validate_machine_std_mvp_import_bundle_set, validate_machine_std_mvp_locators,
    validate_machine_std_mvp_optional_prompt_metadata, validate_machine_std_mvp_prompt_metadata,
    validate_machine_std_mvp_release_final_sidecar_counts,
    validate_machine_std_mvp_rewrite_profile_set, validate_machine_std_mvp_simp_profile_set,
    validate_machine_std_mvp_theorem_index, MachineStdArtifactKind, MachineStdArtifactShapeError,
    MachineStdArtifactShapeErrorReason, MachineStdAttribute, MachineStdAuditArtifacts,
    MachineStdAuditCheck, MachineStdAuditError, MachineStdAuditReport, MachineStdAxiomPolicyError,
    MachineStdAxiomRef, MachineStdAxiomReport, MachineStdCanonicalBytesError, MachineStdGlobalRef,
    MachineStdGlobalRefView, MachineStdImportBundle, MachineStdImportBundleError,
    MachineStdImportBundleSet, MachineStdImportCertificate, MachineStdLibraryRelease,
    MachineStdLibraryReleaseError, MachineStdLoadedModule, MachineStdLoadedRelease,
    MachineStdLocatorPathError, MachineStdModuleArtifact, MachineStdModuleAxiomReport,
    MachineStdModuleLocator, MachineStdPromptExample, MachineStdPromptMetadata,
    MachineStdPromptMetadataError, MachineStdPromptMetadataSet, MachineStdReleaseArtifactError,
    MachineStdReleaseLoaderError, MachineStdReleaseSidecarJson, MachineStdRewriteDescriptor,
    MachineStdRewriteProfile, MachineStdRewriteProfileError, MachineStdRewriteProfileSet,
    MachineStdRewriteSafety, MachineStdSimpProfile, MachineStdSimpProfileError,
    MachineStdSimpProfileSet, MachineStdTacticOptionsRecipe, MachineStdTheoremEntry,
    MachineStdTheoremIndex, MachineStdTheoremIndexError, MachineStdTheoremKind,
    MachineStdValidatedRelease,
};
pub use tactic::{
    parse_machine_tactic_batch_request, parse_machine_tactic_run_request,
    run_machine_tactic_batch_request, run_machine_tactic_batch_request_in_sessions,
    run_machine_tactic_request, run_machine_tactic_request_in_sessions,
    MachineBatchSchedulerLimits, MachineRunSchedulerLimits, MachineTacticBatchCandidateRequest,
    MachineTacticBatchError, MachineTacticBatchItemResponse, MachineTacticBatchOkFields,
    MachineTacticBatchRequest, MachineTacticBatchResponse, MachineTacticBatchSchedulerFields,
    MachineTacticRunDeltaSummary, MachineTacticRunError, MachineTacticRunErrorFields,
    MachineTacticRunErrorObject, MachineTacticRunRequest, MachineTacticRunResponse,
    MachineTacticRunResultKind, MachineTacticRunSchedulerFields, MachineTacticRunSuccessFields,
    MachineTacticRunSuccessResult,
};
pub use types::{
    format_goal_id_wire, format_hash_string, format_meta_var_id_wire, is_machine_local_name,
    is_machine_surface_name_component, is_machine_surface_renderable_name_wire,
    is_machine_surface_term_head_component, is_machine_universe_param_name,
    machine_endpoint_envelope_spec, parse_fully_qualified_name_wire, parse_goal_id_wire,
    parse_hash_string, parse_local_id_wire, parse_machine_surface_renderable_name_wire,
    parse_machine_universe_param_name, parse_meta_var_id_wire, parse_module_name_wire,
    parse_phase5_name, phase5_name_canonical_bytes, validate_delete_session_request,
    validate_machine_endpoint_envelope, CheckedMachineProofRoot, HashString, KernelCheckProfileId,
    MachineApiCompactErrorWire, MachineApiEndpoint, MachineApiErrorResponse, MachineApiErrorWire,
    MachineApiOkResponse, MachineApiOptions, MachineApiResponseEnvelope, MachineApiResponseStatus,
    MachineApiSchedulerResponse, MachineApiVersion, MachineEndpointEnvelopeSpec,
    MachineEndpointFieldSpec, MachineEndpointFieldType, MachineGoalView, MachineLocalView,
    MachineProofSession, MachineProofSnapshot, MachineRootTermSource, MachineSchedulerArtifact,
    MachineSchedulerArtifactKind, MachineSchedulerArtifactScope,
    MachineTacticOptionsConversionError, MachineTacticOptionsRequest,
    MachineValidatedEndpointEnvelope, MachineWireGrammarError, MachineWireGrammarErrorKind,
    SessionId, SnapshotId, KERNEL_CHECK_PROFILE_BUILTIN_NAT_EQ_REC,
    KERNEL_CHECK_PROFILE_BUILTIN_NONE, MACHINE_API_VERSION, MACHINE_DISPLAY_PROFILE_ID,
    MACHINE_TACTIC_CANDIDATE_OUTPUT_SCHEMA,
};
pub use validation::{
    delayed_json_payload, parse_request_body, parse_request_body_with_limits,
    parse_strict_u64_token, validate_json_object, DelayedJsonPayload, FieldSpec, JsonFieldType,
    JsonPath, JsonPathElement, MachineApiErrorKind, MachineApiRequestError,
    MachineApiRequestErrorReason, ObjectSchema, StrictUnsignedIntegerError, ValidatedObject,
};
pub use verify::{
    parse_machine_verify_request, run_machine_verify_request,
    run_machine_verify_request_in_sessions, MachineCertificateWirePayload,
    MachineVerifiedModuleCertificatePayload, MachineVerifyError, MachineVerifyOkFields,
    MachineVerifyRequest, MachineVerifyResponse,
};
