//! Machine API substrate.
//!
//! This crate is intentionally outside the trusted kernel. It handles wire JSON
//! decoding and request-shape validation for machine-facing endpoints.
//! Machine tactic, machine API, and AI search candidate APIs operate on `MachineTacticCandidate`; certificate
//! producer fast-path candidates remain in `npa-cert` until a separate upper-crate
//! bridge is designed.
//!
//! ```compile_fail
//! use npa_api::ai_search_candidate_payload_hash;
//! use npa_cert::CoreDeclCandidate;
//!
//! let candidate: &CoreDeclCandidate = unimplemented!();
//! let _ = ai_search_candidate_payload_hash(candidate);
//! ```

mod adapter;
mod advanced_ai;
mod ai_search;
mod callable;
mod current;
mod diagnostic;
mod human;
mod human_ide;
mod independent_checker;
mod json;
mod projection;
mod prompt;
mod renderer;
mod replay;
mod search;
mod session;
mod snapshot;
mod std_library;
mod tactic;
mod types;
mod validation;
mod verify;

pub use adapter::{
    machine_tactic_extract_closed_machine_theorem_decl, machine_tactic_machine_tactic_result_error,
    machine_tactic_run_machine_tactic, machine_tactic_run_machine_tactic_with_budget,
    machine_tactic_start_machine_proof, machine_tactic_validate_machine_tactic_candidate,
    map_frontend_diagnostic_kind, map_machine_tactic_diagnostic_kind, MachineApiDiagnosticPhase,
    MachineApiDiagnosticProjection, MachineApiTacticKind, MachineApiUpstreamDiagnostic,
    MachineTacticAdapterError, MachineTacticAdapterResult, MachineTacticExtractedTheorem,
    MachineTacticRunOutput, MachineTacticStartProofOutput, ValidatedMachineTactic,
};
pub use advanced_ai::{
    advanced_ai_candidate_envelope_canonical_bytes, advanced_ai_candidate_hash,
    advanced_ai_env_fingerprint, advanced_ai_file_hash,
    advanced_ai_formalization_accepted_statement_hash,
    advanced_ai_formalization_candidate_statement_hash, advanced_ai_formalization_claim_span_hash,
    advanced_ai_formalization_payload_canonical_bytes, advanced_ai_formalization_proof_root_hash,
    advanced_ai_formalization_rejection_reason_hash,
    advanced_ai_formalization_source_document_hash, advanced_ai_goal_canonical_bytes,
    advanced_ai_goal_fingerprint, advanced_ai_inductive_proposal_canonical_bytes,
    advanced_ai_options_canonical_bytes, advanced_ai_options_hash,
    advanced_ai_quotient_candidate_canonical_bytes, advanced_ai_smt_candidate_canonical_bytes,
    advanced_ai_smt_command_id, advanced_ai_smt_encoding_hash,
    advanced_ai_smt_problem_canonical_bytes, advanced_ai_smt_problem_hash,
    advanced_ai_smt_proof_payload_canonical_bytes, advanced_ai_smt_proof_payload_hash,
    advanced_ai_smt_symbol_canonical_bytes, advanced_ai_theorem_graph_query_canonical_bytes,
    advanced_ai_theorem_graph_query_features_canonical_bytes,
    advanced_ai_theorem_graph_query_features_hash,
    advanced_ai_theorem_graph_snapshot_canonical_bytes, advanced_ai_theorem_graph_snapshot_hash,
    advanced_ai_typeclass_resolution_plan_canonical_bytes,
    advanced_ai_universe_repair_candidate_canonical_bytes,
    advanced_ai_validation_result_hash_for_rejection,
    advanced_ai_validation_result_hash_for_success, run_advanced_ai_formalize_check_request,
    run_advanced_ai_inductive_check_request, run_advanced_ai_quotient_check_request,
    run_advanced_ai_smt_reconstruct_request, run_advanced_ai_theorem_graph_query_request,
    run_advanced_ai_typeclass_resolve_request, run_advanced_ai_universe_repair_check_request,
    validate_advanced_ai_common_envelope, AdvancedAiCandidateEnvelope, AdvancedAiCanonicalError,
    AdvancedAiEndpointError, AdvancedAiEndpointResponse, AdvancedAiFeatureError,
    AdvancedAiGlobalRef, AdvancedAiGoal, AdvancedAiOptions, AdvancedAiOptionsRef,
    AdvancedAiOptionsVersion, AdvancedAiProfileVersion, AdvancedAiSuccessPayload, AdvancedAiTarget,
    AdvancedAiTaskKind, AdvancedAiValidationError, AdvancedFormalizationError,
    AdvancedFormalizationIntentRecord, AdvancedFormalizationIntentStatus,
    AdvancedFormalizationOptions, AdvancedFormalizationSuccessKind, AdvancedImportIdentity,
    AdvancedIndependentCheckerOptions, AdvancedIndependentCheckerProfile, AdvancedInductiveError,
    AdvancedInductiveOptions, AdvancedMachineConstructorProposal, AdvancedMachineExprOccurrence,
    AdvancedMachineExprPathStep, AdvancedMachineFormalizationCandidate,
    AdvancedMachineFormalizationCheckPayload, AdvancedMachineFormalizationClaimSpan,
    AdvancedMachineFormalizationProofCandidate, AdvancedMachineFormalizationRejectionReasonRef,
    AdvancedMachineFormalizationSourceDocumentRef, AdvancedMachineInductiveFamilyProposal,
    AdvancedMachineInductiveProposal, AdvancedMachineInstanceCandidateRef,
    AdvancedMachineInstanceTargetRef, AdvancedMachineQuotientConstructionCandidate,
    AdvancedMachineQuotientOperationCandidate, AdvancedMachineSmtCertificateCandidate,
    AdvancedMachineSmtEncodedProblem, AdvancedMachineSmtPayloadBinding,
    AdvancedMachineSmtProblemRef, AdvancedMachineSmtProofPayloadRef,
    AdvancedMachineSmtReconstructionPlan, AdvancedMachineSmtReconstructionStep,
    AdvancedMachineSurfaceTerm, AdvancedMachineTelescopeBinder, AdvancedMachineTheoremGraphEdge,
    AdvancedMachineTheoremGraphFeature, AdvancedMachineTheoremGraphNodeRef,
    AdvancedMachineTheoremGraphQuery, AdvancedMachineTheoremGraphQueryFeatures,
    AdvancedMachineTheoremGraphQueryFeaturesRef, AdvancedMachineTheoremGraphResult,
    AdvancedMachineTheoremGraphResultEntry, AdvancedMachineTheoremGraphScore,
    AdvancedMachineTheoremGraphSnapshot, AdvancedMachineTheoremGraphSnapshotRef,
    AdvancedMachineTheoremGraphSnapshotSource, AdvancedMachineTypeclassResolutionPlan,
    AdvancedQuotientConstructionError, AdvancedQuotientOptions, AdvancedReviewerId,
    AdvancedSmtBuiltinOp, AdvancedSmtCertificateError, AdvancedSmtCertificateFormat,
    AdvancedSmtCommandPayload, AdvancedSmtCommandPhase, AdvancedSmtCommandProfile,
    AdvancedSmtConclusionEncoding, AdvancedSmtDatatypeConstructor, AdvancedSmtDatatypeSelector,
    AdvancedSmtEncodedCommand, AdvancedSmtEncoderVersion, AdvancedSmtExpr,
    AdvancedSmtLocalBookkeepingRule, AdvancedSmtLogic, AdvancedSmtOptions, AdvancedSmtProofNode,
    AdvancedSmtProofNodeTable, AdvancedSmtReconstructionRule, AdvancedSmtRuleRegistryProfile,
    AdvancedSmtSortExpr, AdvancedSmtSymbol, AdvancedTheoremGraphEdgeKind,
    AdvancedTheoremGraphError, AdvancedTheoremGraphExtractorVersion,
    AdvancedTheoremGraphFeatureKey, AdvancedTheoremGraphFeatureSchemaVersion,
    AdvancedTheoremGraphFeatureValue, AdvancedTheoremGraphRankingProfile, AdvancedTypeclassOptions,
    AdvancedTypeclassResolutionError, AdvancedUniverseConstraint, AdvancedUniverseConstraintHint,
    AdvancedUniverseConstraintHintReason, AdvancedUniverseConstraintRelation,
    AdvancedUniverseInstantiationPatch, AdvancedUniverseMinimizationHint,
    AdvancedUniverseRepairCandidate, AdvancedUniverseRepairError, AdvancedValidatedCommonEnvelope,
    ADVANCED_AI_FORMALIZE_CHECK_ENDPOINT, ADVANCED_AI_INDUCTIVE_CHECK_ENDPOINT,
    ADVANCED_AI_QUOTIENT_CHECK_ENDPOINT, ADVANCED_AI_SMT_RECONSTRUCT_ENDPOINT,
    ADVANCED_AI_THEOREM_GRAPH_QUERY_ENDPOINT, ADVANCED_AI_TYPECLASS_RESOLVE_ENDPOINT,
    ADVANCED_AI_UNIVERSE_REPAIR_CHECK_ENDPOINT,
};
pub use ai_search::{
    ai_search_assign_candidate_ids, ai_search_build_replay_plan,
    ai_search_builtin_candidate_envelopes, ai_search_candidate_cost_estimate,
    ai_search_candidate_envelope, ai_search_candidate_forbidden_token,
    ai_search_candidate_hash_mismatch, ai_search_candidate_payload_hash,
    ai_search_candidate_payload_json, ai_search_cap_batch_policy,
    ai_search_evaluate_tactic_batch_response, ai_search_expected_effect,
    ai_search_fresh_intro_name, ai_search_goal_summaries, ai_search_minimize_replay_plan,
    ai_search_mvp_candidate_envelopes, ai_search_mvp_candidate_generation,
    ai_search_mvp_premise_query_json, ai_search_negative_training_identity,
    ai_search_negative_training_identity_hash, ai_search_negative_training_identity_json,
    ai_search_node_best_partial_key, ai_search_node_priority_key,
    ai_search_positive_training_identity, ai_search_positive_training_identity_hash,
    ai_search_positive_training_identity_json, ai_search_premise_cache_entries,
    ai_search_premise_retrieval_from_search_ok, ai_search_premise_usages,
    ai_search_rank_and_dedupe_candidate_envelopes,
    ai_search_rank_filter_and_dedupe_candidate_envelopes, ai_search_repair_depth_of,
    ai_search_replay_plan_json, ai_search_replay_request_json, ai_search_replay_step_json,
    ai_search_retrieval_cache_key, ai_search_rule_based_repair_action, ai_search_run_mvp_search,
    ai_search_run_tactic_batch, ai_search_snapshot_get_request_json,
    ai_search_suggested_candidate_envelopes, ai_search_tactic_batch_request_json,
    ai_search_training_trace_record_json, ai_search_training_trace_records_json,
    ai_search_verify_request_json, filter_ai_search_candidate_envelopes,
    load_ai_search_initial_snapshot, parse_ai_search_mvp_controller_config,
    retrieve_ai_search_premises, select_ai_search_goal, validate_ai_search_mvp_controller_config,
    AiSearchAcceptedCandidateFailure, AiSearchAcceptedCandidateFailureRecord,
    AiSearchAssignedCandidate, AiSearchBatchEvaluation, AiSearchBestPartialKey, AiSearchBudget,
    AiSearchBudgetLimit, AiSearchBuiltinKind, AiSearchCandidateCostEstimate,
    AiSearchCandidateCostRisk, AiSearchCandidateEnvelope, AiSearchCandidateFilterError,
    AiSearchCandidateFilterResult, AiSearchCandidateMetadata, AiSearchCandidateRankMetadata,
    AiSearchCandidateRepairMetadata, AiSearchCandidateSource, AiSearchDeferredCandidate,
    AiSearchDeferredCandidateDropReason, AiSearchExpectedEffect, AiSearchFailure,
    AiSearchFailureReason, AiSearchFakeMachineApiClient, AiSearchForbiddenToken,
    AiSearchForbiddenTokenClass, AiSearchGoalSummary, AiSearchInitialSnapshot, AiSearchInput,
    AiSearchLocalMachineApiClient, AiSearchMachineApiCall, AiSearchMachineApiClient,
    AiSearchMachineApiEndpointKind, AiSearchMachineApiError, AiSearchMachineApiResult,
    AiSearchMachineControllerError, AiSearchMachineControllerErrorKind,
    AiSearchMachineControllerResult, AiSearchMinimizationResult, AiSearchMinimizationStats,
    AiSearchMvpControllerConfig, AiSearchNegativeTrainingIdentity, AiSearchNode, AiSearchNodeId,
    AiSearchNodeStatus, AiSearchNonAcceptedCandidateError, AiSearchPendingCandidate,
    AiSearchPositiveTrainingIdentity, AiSearchPremiseCacheEntry, AiSearchPremiseQueryRequest,
    AiSearchPremiseRef, AiSearchPremiseRetrieval, AiSearchPremiseUsage, AiSearchPriorityKey,
    AiSearchRejectedCandidateEnvelope, AiSearchRepairCandidateOutput,
    AiSearchRepairChainStopReason, AiSearchReplayPlan, AiSearchReplayStep, AiSearchReplayStepEdit,
    AiSearchResult, AiSearchRetrievalCacheKey, AiSearchRuleBasedRepair,
    AiSearchRuleBasedRepairAction, AiSearchSchedulerStop, AiSearchScore,
    AiSearchSnapshotGetRequest, AiSearchStats, AiSearchSuccessfulCandidateTransition,
    AiSearchTacticBatchRequest, AiSearchTacticBatchRunError, AiSearchTraceEvent,
    AiSearchTraceEventKind, AiSearchTrainingTraceCandidate, AiSearchTrainingTraceRecord,
    AiSearchTrustFlags, AiSearchVerifiedProof, AI_SEARCH_TRAINING_TRACE_SCHEMA,
};
pub use callable::{
    build_machine_surface_callable_interface_table,
    build_machine_surface_callable_interface_table_from_parts,
    MachineSurfaceCallableInterfaceBuildError,
};
pub use current::{
    project_checked_current_decl_context, project_checked_current_decl_context_with_kernel_profile,
    CheckedCurrentDeclPackageInput, CheckedCurrentDeclProjectionError, CurrentDeclDependencyEntry,
    CurrentDeclDependencyReport, CurrentDeclIndexEntry, CurrentGeneratedDeclEntry,
    CurrentGeneratedDeclKind, MachineAxiomRefWire, MachineCheckedCurrentDeclContext,
    MachineCheckedDeclSignature, MachineDependencyRefWire,
};
pub use diagnostic::{
    machine_api_diagnostic_canonical_bytes, machine_api_diagnostic_hash,
    MachineApiDiagnosticCanonicalizationError,
};
pub use human::{
    check_human_tactic_term, compile_human_source_to_certificate, compile_human_source_to_core,
    create_human_session, get_current_human_state, get_human_proof_state, get_human_state_at,
    get_human_state_by_id, get_human_state_goals, human_api_default_compile_options,
    materialize_human_proof_state, record_human_tactic_state, run_human_apply_tactic,
    run_human_exact_tactic, run_human_induction_tactic, run_human_intro_tactic,
    run_human_rewrite_tactic, run_human_simp_lite_tactic, run_human_tactic_script,
    start_human_proof, start_human_session_proof, update_human_document,
    validate_human_state_request_document,
};
pub use human_ide::{
    human_ide_api_boundary, HumanIdeApiBoundary, HumanIdeMachineFastPathPolicy,
    HumanIdeMachineSessionPolicy, HUMAN_IDE_API_PROFILE,
};
pub use independent_checker::{
    evaluate_required_ai_sidecar_diagnostics, independent_checker_ai_audit_input_policy_hash,
    independent_checker_ai_audit_prompt_input_for_sidecar,
    independent_checker_ai_sidecar_diagnostic_targets_from_normalized_result,
    independent_checker_argv, independent_checker_auxiliary_axiom_policy_result,
    independent_checker_auxiliary_axiom_policy_result_with_selector,
    independent_checker_auxiliary_command_exit_success,
    independent_checker_auxiliary_import_certificate_hash_result,
    independent_checker_auxiliary_output_write_failure,
    independent_checker_auxiliary_reproducibility_result,
    independent_checker_auxiliary_reproducibility_result_with_selector,
    independent_checker_auxiliary_result_passes_release_condition,
    independent_checker_auxiliary_result_store_entry_for_result,
    independent_checker_auxiliary_result_store_with_entry,
    independent_checker_auxiliary_results_all_passed,
    independent_checker_build_normalized_comparison, independent_checker_canonical_json_bytes,
    independent_checker_canonical_json_object_excluding_top_level_fields,
    independent_checker_canonical_json_string, independent_checker_canonical_json_value_bytes,
    independent_checker_challenge_coverage_summary,
    independent_checker_challenge_coverage_summary_hash, independent_checker_challenge_generate,
    independent_checker_challenge_generation_request_hash,
    independent_checker_challenge_manifest_expected_certificate_hash,
    independent_checker_challenge_manifest_is_rejection_required,
    independent_checker_challenge_materialize_requests,
    independent_checker_challenge_output_store_with_entry,
    independent_checker_challenge_replay_aggregate,
    independent_checker_challenge_replay_result_hash,
    independent_checker_challenge_replay_store_entry_for_result,
    independent_checker_challenge_replay_store_with_entry,
    independent_checker_compare_normalized_result, independent_checker_file_hash,
    independent_checker_first_forbidden_verification_input_field,
    independent_checker_forbids_verification_input_field,
    independent_checker_hash_json_object_excluding_top_level_fields,
    independent_checker_hash_usage_rule, independent_checker_json_artifact_hash_from_source,
    independent_checker_machine_check_request_hash, independent_checker_machine_check_run,
    independent_checker_machine_result_store_entry_for_result,
    independent_checker_machine_result_store_with_entry,
    independent_checker_normalization_write_result, independent_checker_normalize_results,
    independent_checker_normalized_result_store_entry_for_result,
    independent_checker_normalized_result_store_with_entry,
    independent_checker_raw_certificate_claims, independent_checker_raw_claimed_certificate_hash,
    independent_checker_release_bundle, independent_checker_release_policy_hash,
    independent_checker_release_stage_bundle_inputs,
    independent_checker_release_target_has_required_ai_sidecar_diagnostic_targets,
    independent_checker_release_validate_bundle, independent_checker_request_materialize,
    independent_checker_request_store_with_materialized_entry,
    independent_checker_required_ai_sidecar_diagnostic_targets,
    independent_checker_resolve_checker_executable, independent_checker_rfc8785_object_key_cmp,
    independent_checker_runner_fixed_environment, independent_checker_runner_policy_hash,
    independent_checker_sha256, independent_checker_training_export,
    independent_checker_validate_ai_audit_sidecar_cross_artifact,
    independent_checker_validate_ai_audit_sidecar_schema_only,
    independent_checker_validate_release_policy_runner_trust,
    independent_checker_validate_selected_checker_identity_manifest,
    parse_independent_checker_ai_audit_input_policy, parse_independent_checker_ai_audit_sidecar,
    parse_independent_checker_auxiliary_result,
    parse_independent_checker_auxiliary_result_store_manifest,
    parse_independent_checker_axiom_policy_toml, parse_independent_checker_axiom_report,
    parse_independent_checker_axiom_report_store_manifest,
    parse_independent_checker_binary_registry,
    parse_independent_checker_challenge_coverage_summary,
    parse_independent_checker_challenge_generation_request,
    parse_independent_checker_challenge_manifest,
    parse_independent_checker_challenge_output_store_manifest,
    parse_independent_checker_challenge_replay_result,
    parse_independent_checker_challenge_replay_store_manifest,
    parse_independent_checker_identity_manifest, parse_independent_checker_import_lock_manifest,
    parse_independent_checker_machine_check_request,
    parse_independent_checker_machine_result_store_manifest,
    parse_independent_checker_machine_result_store_reference,
    parse_independent_checker_normalized_result_store_manifest,
    parse_independent_checker_raw_result, parse_independent_checker_release_audit_bundle_manifest,
    parse_independent_checker_release_bundle_staging_plan,
    parse_independent_checker_release_policy, parse_independent_checker_request_store_manifest,
    parse_independent_checker_request_store_reference, parse_independent_checker_runner_policy,
    parse_independent_checker_runner_policy_reference, validate_independent_checker_closed_object,
    IndependentCheckerAiAuditInputPolicy, IndependentCheckerAiAuditPromptInput,
    IndependentCheckerAiAuditSidecar, IndependentCheckerAiAuditSidecarAi,
    IndependentCheckerAiAuditSidecarClassification, IndependentCheckerAiAuditSidecarInputPolicy,
    IndependentCheckerAiAuditSidecarSource, IndependentCheckerAiAuditSidecarSourceKind,
    IndependentCheckerAiAuditSidecarStatus, IndependentCheckerAiSidecarDiagnosticError,
    IndependentCheckerAiSidecarDiagnosticEvaluationFailure,
    IndependentCheckerAiSidecarDiagnosticEvaluationFailureReasonCode,
    IndependentCheckerAiSidecarDiagnosticFailureReasonCode,
    IndependentCheckerAiSidecarDiagnosticPassFailure,
    IndependentCheckerAiSidecarDiagnosticPassFailureReasonCode,
    IndependentCheckerAiSidecarDiagnosticResult, IndependentCheckerAiSidecarDiagnosticStatus,
    IndependentCheckerAllowlistEntry, IndependentCheckerApiError,
    IndependentCheckerApiErrorReasonCode, IndependentCheckerArtifactClassification,
    IndependentCheckerArtifactKind, IndependentCheckerArtifactSelector,
    IndependentCheckerAuditSidecarValidationError, IndependentCheckerAuditSidecarValidationMode,
    IndependentCheckerAuditSidecarValidationReasonCode,
    IndependentCheckerAuditSidecarValidationResult, IndependentCheckerAuditSidecarValidationStatus,
    IndependentCheckerAuxiliaryError, IndependentCheckerAuxiliaryReasonCode,
    IndependentCheckerAuxiliaryResult, IndependentCheckerAuxiliaryResultKind,
    IndependentCheckerAuxiliaryResultStoreEntry, IndependentCheckerAuxiliaryResultStoreManifest,
    IndependentCheckerAuxiliaryResultStoreUpdate, IndependentCheckerAuxiliarySelector,
    IndependentCheckerAuxiliaryStatus, IndependentCheckerAxiomPolicy,
    IndependentCheckerAxiomReport, IndependentCheckerAxiomReportEntry,
    IndependentCheckerAxiomReportStoreEntry, IndependentCheckerAxiomReportStoreManifest,
    IndependentCheckerBinaryRegistry, IndependentCheckerBinaryRegistryEntry,
    IndependentCheckerBinaryRegistryRootKind, IndependentCheckerCanonicalJsonError,
    IndependentCheckerChallengeBaseCertificate, IndependentCheckerChallengeCoverageEntry,
    IndependentCheckerChallengeCoverageSummary, IndependentCheckerChallengeGeneratedBy,
    IndependentCheckerChallengeGeneratedByKind, IndependentCheckerChallengeGeneratedCertificate,
    IndependentCheckerChallengeGeneration, IndependentCheckerChallengeGenerationOutput,
    IndependentCheckerChallengeGenerationRequest, IndependentCheckerChallengeGenerationResult,
    IndependentCheckerChallengeImports, IndependentCheckerChallengeManifest,
    IndependentCheckerChallengeManifestReference,
    IndependentCheckerChallengeMaterializedRequestEntry,
    IndependentCheckerChallengeMutatedCertificate, IndependentCheckerChallengeMutation,
    IndependentCheckerChallengeMutationKind, IndependentCheckerChallengeOutcomeHint,
    IndependentCheckerChallengeOutputStoreEntry, IndependentCheckerChallengeOutputStoreManifest,
    IndependentCheckerChallengeOutputStoreReference, IndependentCheckerChallengeOutputStoreUpdate,
    IndependentCheckerChallengeReplayAggregation, IndependentCheckerChallengeReplayCheckerResult,
    IndependentCheckerChallengeReplayMetadata, IndependentCheckerChallengeReplayResult,
    IndependentCheckerChallengeReplayStoreEntry, IndependentCheckerChallengeReplayStoreManifest,
    IndependentCheckerChallengeReplayStoreUpdate,
    IndependentCheckerChallengeRequestMaterialization,
    IndependentCheckerChallengeRequestMaterializationResult,
    IndependentCheckerCiDiagnosticTargetContext, IndependentCheckerClosedSchema,
    IndependentCheckerCommandError, IndependentCheckerCommandName,
    IndependentCheckerCompareValidationError, IndependentCheckerCompareValidationErrorKind,
    IndependentCheckerCompareValidationResult, IndependentCheckerCompareValidationStatus,
    IndependentCheckerFieldSpec, IndependentCheckerHashInputKind, IndependentCheckerHashUsageKind,
    IndependentCheckerHashUsageRule, IndependentCheckerIdentityEntry,
    IndependentCheckerIdentityGeneratedBy, IndependentCheckerIdentityManifest,
    IndependentCheckerIdentityManifestReference, IndependentCheckerImportLockCertificate,
    IndependentCheckerImportLockEntry, IndependentCheckerImportLockManifest,
    IndependentCheckerJsonFieldType, IndependentCheckerJsonPath, IndependentCheckerJsonPathElement,
    IndependentCheckerMachineCheckChecker, IndependentCheckerMachineCheckError,
    IndependentCheckerMachineCheckProcess, IndependentCheckerMachineCheckRequest,
    IndependentCheckerMachineCheckRequestCertificate,
    IndependentCheckerMachineCheckRequestErrorReasonCode,
    IndependentCheckerMachineCheckRequestErrorResult, IndependentCheckerMachineCheckRequestImports,
    IndependentCheckerMachineCheckRequestPolicy, IndependentCheckerMachineCheckResourceUsage,
    IndependentCheckerMachineCheckResult, IndependentCheckerMachineCheckRunner,
    IndependentCheckerMachineCheckStatus, IndependentCheckerMachineResultStoreEntry,
    IndependentCheckerMachineResultStoreManifest, IndependentCheckerMachineResultStoreReference,
    IndependentCheckerMachineResultStoreUpdate, IndependentCheckerNormalizationWriteResult,
    IndependentCheckerNormalizationWriteStore, IndependentCheckerNormalizeErrorReasonCode,
    IndependentCheckerNormalizeErrorResult, IndependentCheckerNormalizedArtifact,
    IndependentCheckerNormalizedCheckResult, IndependentCheckerNormalizedCheckResultEntry,
    IndependentCheckerNormalizedComparison, IndependentCheckerNormalizedComparisonStatus,
    IndependentCheckerNormalizedDisagreement, IndependentCheckerNormalizedFailureKey,
    IndependentCheckerNormalizedResultStoreEntry, IndependentCheckerNormalizedResultStoreManifest,
    IndependentCheckerNormalizedResultStoreUpdate, IndependentCheckerNormalizedStatusReason,
    IndependentCheckerPipelineErrorKind, IndependentCheckerPolicyFailure,
    IndependentCheckerPolicyFailureReasonCode, IndependentCheckerPolicyValidationError,
    IndependentCheckerRawCertificateClaims, IndependentCheckerRawResult,
    IndependentCheckerRawResultSchemaError, IndependentCheckerReleaseAuditBundleArtifact,
    IndependentCheckerReleaseAuditBundleManifest, IndependentCheckerReleaseBundleArtifactKind,
    IndependentCheckerReleaseBundleGeneration, IndependentCheckerReleaseBundleStagedArtifact,
    IndependentCheckerReleaseBundleStagedFile, IndependentCheckerReleaseBundleStagedStoreManifest,
    IndependentCheckerReleaseBundleStaging, IndependentCheckerReleaseBundleStagingInput,
    IndependentCheckerReleaseBundleStagingPhase, IndependentCheckerReleaseBundleStagingPlan,
    IndependentCheckerReleaseBundleStagingResult, IndependentCheckerReleaseBundleValidation,
    IndependentCheckerReleaseMode, IndependentCheckerReleasePolicy,
    IndependentCheckerReleasePolicyAiTriage, IndependentCheckerRequestMaterialization,
    IndependentCheckerRequestStoreEntry, IndependentCheckerRequestStoreManifest,
    IndependentCheckerRequestStoreReference, IndependentCheckerRequestStoreUpdate,
    IndependentCheckerRequestValidationError,
    IndependentCheckerRequiredAiSidecarDiagnosticEvaluation,
    IndependentCheckerRequiredAiSidecarDiagnosticTarget,
    IndependentCheckerRequiredAiSidecarDiagnosticTargetKind,
    IndependentCheckerResolvedAiAuditSidecarEntry,
    IndependentCheckerResolvedAiSidecarDiagnosticResultEntry,
    IndependentCheckerResolvedAuditSidecarValidationEntry,
    IndependentCheckerResolvedCheckerExecutable, IndependentCheckerRunObservation,
    IndependentCheckerRunnerAxiomPolicy, IndependentCheckerRunnerBudget,
    IndependentCheckerRunnerDynamicArgs, IndependentCheckerRunnerImportPolicy,
    IndependentCheckerRunnerPolicy, IndependentCheckerRunnerPolicyReference,
    IndependentCheckerSchemaError, IndependentCheckerSchemaErrorReason,
    IndependentCheckerStoredMachineCheckRequest, IndependentCheckerStructuredError,
    IndependentCheckerTrainingExample, IndependentCheckerTrainingExampleIdentity,
    IndependentCheckerTrainingExampleInput, IndependentCheckerTrainingExampleLabel,
    IndependentCheckerTrainingExampleSource, IndependentCheckerTrainingExport,
    IndependentCheckerTrainingExportManifest, IndependentCheckerTrainingExportSources,
    IndependentCheckerTrustMode, IndependentCheckerValidatedObject,
    INDEPENDENT_CHECKER_AI_AUDIT_INPUT_POLICY_SCHEMA,
    INDEPENDENT_CHECKER_AI_AUDIT_PROMPT_INPUT_SCHEMA, INDEPENDENT_CHECKER_AI_AUDIT_SIDECAR_SCHEMA,
    INDEPENDENT_CHECKER_AI_SIDECAR_DIAGNOSTIC_EVALUATION_FAILURE_SCHEMA,
    INDEPENDENT_CHECKER_AI_SIDECAR_DIAGNOSTIC_RESULT_SCHEMA, INDEPENDENT_CHECKER_API_ERROR_SCHEMA,
    INDEPENDENT_CHECKER_AUDIT_SIDECAR_VALIDATION_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_AUXILIARY_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_AUXILIARY_RESULT_STORE_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_AXIOM_POLICY_TOML_FORMAT, INDEPENDENT_CHECKER_AXIOM_REPORT_SCHEMA,
    INDEPENDENT_CHECKER_AXIOM_REPORT_STORE_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_CHALLENGE_COVERAGE_SUMMARY_SCHEMA,
    INDEPENDENT_CHECKER_CHALLENGE_GENERATION_REQUEST_SCHEMA,
    INDEPENDENT_CHECKER_CHALLENGE_GENERATION_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_CHALLENGE_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_CHALLENGE_OUTPUT_STORE_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_CHALLENGE_REPLAY_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_CHALLENGE_REPLAY_STORE_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_CHALLENGE_REQUEST_MATERIALIZATION_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_CHECKER_BINARY_REGISTRY_SCHEMA,
    INDEPENDENT_CHECKER_CHECKER_IDENTITY_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_CHECKER_RAW_RESULT_SCHEMA, INDEPENDENT_CHECKER_COMMAND_ERROR_SCHEMA,
    INDEPENDENT_CHECKER_COMPARE_VALIDATION_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_FORBIDDEN_VERIFICATION_INPUT_FIELDS,
    INDEPENDENT_CHECKER_IMPORT_LOCK_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_MACHINE_CHECK_REQUEST_ERROR_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_MACHINE_CHECK_REQUEST_SCHEMA,
    INDEPENDENT_CHECKER_MACHINE_CHECK_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_MACHINE_RESULT_STORE_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_NORMALIZATION_WRITE_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_NORMALIZED_CHECK_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_NORMALIZED_RESULT_STORE_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_NORMALIZE_ERROR_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_RELEASE_AUDIT_BUNDLE_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_RELEASE_BUNDLE_STAGING_PLAN_SCHEMA,
    INDEPENDENT_CHECKER_RELEASE_BUNDLE_STAGING_RESULT_SCHEMA,
    INDEPENDENT_CHECKER_RELEASE_POLICY_SCHEMA, INDEPENDENT_CHECKER_REQUEST_STORE_MANIFEST_SCHEMA,
    INDEPENDENT_CHECKER_RUNNER_DYNAMIC_FLAGS, INDEPENDENT_CHECKER_RUNNER_FIXED_ENVIRONMENT,
    INDEPENDENT_CHECKER_RUNNER_POLICY_SCHEMA, INDEPENDENT_CHECKER_TRAINING_EXAMPLE_SCHEMA,
    INDEPENDENT_CHECKER_TRAINING_EXPORT_MANIFEST_SCHEMA,
};
pub use json::{
    JsonDocument, JsonMember, JsonParseError, JsonParseErrorKind, JsonParseLimits, JsonSpan,
    JsonValue, JsonValueKind,
};
pub use projection::{
    project_import_certificate_context, GeneratedDeclKind, ImportProjectionError,
    MachineImportCertificateContext, VerifiedImportDeclIndexEntry,
    VerifiedImportGeneratedDeclEntry, VerifiedImportGeneratedDeclPayload, VerifiedImportKey,
    VerifiedModuleCertificateInput, VerifiedModuleContextEntry,
};
pub use prompt::{
    build_machine_prompt_payload, build_machine_prompt_payload_in_sessions,
    parse_machine_prompt_payload_request, FailedCandidateErrorKind, FailedCandidatePromptItem,
    MachinePromptGoal, MachinePromptLocal, MachinePromptPayloadError, MachinePromptPayloadOkFields,
    MachinePromptPayloadRequest, MachinePromptPayloadResponse, MachinePromptPremise,
    MachinePromptPremiseSelection,
};
pub use renderer::{
    core_expr_metadata, render_machine_expr_source, render_machine_expr_view,
    renderer_qa_round_trip, CoreExprMetadata, LocalId, MachineApiResolvedDisplayCoreRefOwner,
    MachineDisplayRenderScope, MachineDisplayRenderScopeEntry, MachineExprRendererContext,
    MachineExprRendererError, MachineExprView, MachineGlobalRefView,
};
pub use replay::{
    parse_machine_replay_request, run_machine_replay_request,
    run_machine_replay_request_in_sessions, MachineReplayError, MachineReplayOkFields,
    MachineReplayPlan, MachineReplayRequest, MachineReplayResponse, MachineReplayStep,
};
pub use search::{
    parse_machine_theorem_search_request, search_machine_theorems_for_goal,
    search_machine_theorems_for_goal_in_sessions, MachineAllowedModulesFilter,
    MachineSuggestedCandidate, MachineSuggestedCandidateStatus, MachineTheoremFilters,
    MachineTheoremGlobalRef, MachineTheoremMode, MachineTheoremSearchError,
    MachineTheoremSearchOkFields, MachineTheoremSearchRequest, MachineTheoremSearchResponse,
    MachineTheoremSearchResult, MachineTheoremStatement,
};
pub use session::{
    create_machine_session, MachineSessionCreateError, MachineSessionCreateOk,
    MachineSessionCreateRequest,
};
pub use snapshot::{
    get_machine_snapshot, get_machine_snapshot_from_session, materialize_machine_proof_snapshot,
    parse_machine_snapshot_get_request, stored_snapshot_view_canonical_bytes,
    MachineSnapshotGetError, MachineSnapshotGetOk, MachineSnapshotGetRequest,
    MachineSnapshotLookupError, MachineSnapshotMaterializationContext,
    MachineSnapshotMaterializationError, MachineSnapshotStore, MachineSnapshotStoreError,
    StoredSnapshotEntry, StoredSnapshotView,
};
pub use std_library::{
    audit_machine_std_mvp_release_artifacts, audit_machine_std_mvp_validated_release,
    finalize_machine_std_mvp_import_bundle_recipes, finalize_machine_std_mvp_theorem_index,
    generate_machine_std_mvp_final_import_bundle_set, generate_machine_std_mvp_final_theorem_index,
    generate_machine_std_mvp_import_bundle_set, generate_machine_std_mvp_rewrite_profile_set,
    generate_machine_std_mvp_simp_profile_set, generate_machine_std_mvp_theorem_index,
    load_machine_std_certificates_from_locators, load_machine_std_mvp_certificates,
    load_machine_std_mvp_release,
    load_machine_std_mvp_release_with_optional_prompt_metadata_from_json,
    load_machine_std_mvp_release_with_sidecars_from_json, machine_std_audit_check_canonical_bytes,
    machine_std_audit_report_canonical_bytes, machine_std_audit_report_hash,
    machine_std_axiom_ref_canonical_bytes, machine_std_axiom_report_canonical_bytes,
    machine_std_axiom_report_hash, machine_std_global_ref_canonical_bytes,
    machine_std_global_ref_view_canonical_bytes, machine_std_import_bundle_canonical_bytes,
    machine_std_import_bundle_hash, machine_std_import_bundle_set_canonical_bytes,
    machine_std_import_bundle_set_hash, machine_std_library_release_canonical_bytes,
    machine_std_library_release_hash, machine_std_module_artifact_canonical_bytes,
    machine_std_mvp_module_locators, machine_std_prompt_example_canonical_bytes,
    machine_std_prompt_metadata_canonical_bytes, machine_std_prompt_metadata_hash,
    machine_std_prompt_metadata_set_canonical_bytes,
    machine_std_rewrite_descriptor_canonical_bytes, machine_std_rewrite_profile_canonical_bytes,
    machine_std_rewrite_profile_hash, machine_std_rewrite_profile_set_canonical_bytes,
    machine_std_rewrite_profile_set_hash, machine_std_rule_telescope_canonical_bytes,
    machine_std_rule_telescope_hash, machine_std_simp_profile_canonical_bytes,
    machine_std_simp_profile_hash, machine_std_simp_profile_set_canonical_bytes,
    machine_std_simp_profile_set_hash, machine_std_tactic_options_recipe_canonical_bytes,
    machine_std_tactic_options_recipe_request, machine_std_theorem_entry_canonical_bytes,
    machine_std_theorem_index_canonical_bytes, machine_std_theorem_index_hash,
    parse_machine_std_axiom_report_json, parse_machine_std_import_bundle_set_json,
    parse_machine_std_library_release_json, parse_machine_std_prompt_metadata_json,
    parse_machine_std_rewrite_profile_set_json, parse_machine_std_simp_profile_set_json,
    parse_machine_std_theorem_index_json, validate_machine_std_locator_path,
    validate_machine_std_mvp_final_theorem_index, validate_machine_std_mvp_import_bundle_recipes,
    validate_machine_std_mvp_import_bundle_set, validate_machine_std_mvp_locators,
    validate_machine_std_mvp_optional_prompt_metadata, validate_machine_std_mvp_prompt_metadata,
    validate_machine_std_mvp_release_final_sidecar_counts,
    validate_machine_std_mvp_rewrite_profile_set, validate_machine_std_mvp_simp_profile_set,
    validate_machine_std_mvp_theorem_index, MachineStdArtifactKind, MachineStdArtifactShapeError,
    MachineStdArtifactShapeErrorReason, MachineStdAttribute, MachineStdAuditArtifacts,
    MachineStdAuditCheck, MachineStdAuditError, MachineStdAuditReport, MachineStdAxiomPolicyError,
    MachineStdAxiomRef, MachineStdAxiomReport, MachineStdCanonicalBytesError, MachineStdGlobalRef,
    MachineStdGlobalRefView, MachineStdImportBundle, MachineStdImportBundleError,
    MachineStdImportBundleSet, MachineStdImportCertificate, MachineStdLibraryRelease,
    MachineStdLibraryReleaseError, MachineStdLoadedModule, MachineStdLoadedRelease,
    MachineStdLocatorPathError, MachineStdModuleArtifact, MachineStdModuleAxiomReport,
    MachineStdModuleLocator, MachineStdPromptExample, MachineStdPromptMetadata,
    MachineStdPromptMetadataError, MachineStdPromptMetadataSet, MachineStdReleaseArtifactError,
    MachineStdReleaseLoaderError, MachineStdReleaseSidecarJson, MachineStdRewriteDescriptor,
    MachineStdRewriteProfile, MachineStdRewriteProfileError, MachineStdRewriteProfileSet,
    MachineStdRewriteSafety, MachineStdSimpProfile, MachineStdSimpProfileError,
    MachineStdSimpProfileSet, MachineStdTacticOptionsRecipe, MachineStdTheoremEntry,
    MachineStdTheoremIndex, MachineStdTheoremIndexError, MachineStdTheoremKind,
    MachineStdValidatedRelease,
};
pub use tactic::{
    parse_machine_tactic_batch_request, parse_machine_tactic_run_request,
    run_machine_tactic_batch_request, run_machine_tactic_batch_request_in_sessions,
    run_machine_tactic_request, run_machine_tactic_request_in_sessions,
    MachineBatchSchedulerLimits, MachineRunSchedulerLimits, MachineTacticBatchCandidateRequest,
    MachineTacticBatchError, MachineTacticBatchItemResponse, MachineTacticBatchOkFields,
    MachineTacticBatchRequest, MachineTacticBatchResponse, MachineTacticBatchSchedulerFields,
    MachineTacticRunDeltaSummary, MachineTacticRunError, MachineTacticRunErrorFields,
    MachineTacticRunErrorObject, MachineTacticRunRequest, MachineTacticRunResponse,
    MachineTacticRunResultKind, MachineTacticRunSchedulerFields, MachineTacticRunSuccessFields,
    MachineTacticRunSuccessResult,
};
pub use types::{
    format_goal_id_wire, format_hash_string, format_meta_var_id_wire, is_machine_local_name,
    is_machine_surface_name_component, is_machine_surface_renderable_name_wire,
    is_machine_surface_term_head_component, is_machine_universe_param_name,
    machine_api_name_canonical_bytes, machine_endpoint_envelope_spec,
    parse_fully_qualified_name_wire, parse_goal_id_wire, parse_hash_string, parse_local_id_wire,
    parse_machine_api_name, parse_machine_surface_renderable_name_wire,
    parse_machine_universe_param_name, parse_meta_var_id_wire, parse_module_name_wire,
    validate_delete_session_request, validate_machine_endpoint_envelope, CheckedMachineProofRoot,
    HashString, HumanApiCompileOptions, HumanApplyTacticError, HumanApplyTacticOk,
    HumanApplyTacticRequest, HumanCompileCertificateOk, HumanCompileCertificateRequest,
    HumanCompileCoreOk, HumanCompileCoreRequest, HumanCompileError, HumanCurrentModuleSource,
    HumanDocumentId, HumanDocumentSnapshot, HumanDocumentUpdateError, HumanDocumentUpdateOk,
    HumanDocumentUpdateRequest, HumanDocumentVersion, HumanExactTacticOk, HumanExactTacticRequest,
    HumanGoalId, HumanGoalMapping, HumanInductionTacticError, HumanInductionTacticOk,
    HumanInductionTacticRequest, HumanIntroTacticError, HumanIntroTacticOk,
    HumanIntroTacticRequest, HumanProofSession, HumanProofSessionStatus, HumanProofSessionStore,
    HumanProofStateEntry, HumanProofStateStartError, HumanProofStateStartOk,
    HumanProofStateStartRequest, HumanProofStateStore, HumanRewriteTacticError,
    HumanRewriteTacticOk, HumanRewriteTacticRequest, HumanSessionCreateError, HumanSessionCreateOk,
    HumanSessionCreateRequest, HumanSessionId, HumanSimpLiteTacticError, HumanSimpLiteTacticOk,
    HumanSimpLiteTacticRequest, HumanSourcePosition, HumanStartProofError, HumanStartProofOk,
    HumanStartProofRequest, HumanStateApiError, HumanStateAtRequest, HumanStateByIdRequest,
    HumanStateCurrentRequest, HumanStateGoalSummary, HumanStateGoalsOk, HumanStateGoalsRequest,
    HumanStateId, HumanStateLookupOk, HumanStateRequestError, HumanStateRequestHeader,
    HumanStructuredProofStateError, HumanTacticScriptError, HumanTacticScriptRunOk,
    HumanTacticScriptRunRequest, HumanTacticStateRecordError, HumanTacticStateRecordOk,
    HumanTacticStateRecordRequest, HumanTacticTermCheckOk, HumanTacticTermCheckRequest,
    HumanTacticTermError, KernelCheckProfileId, MachineApiCompactErrorWire, MachineApiEndpoint,
    MachineApiErrorResponse, MachineApiErrorWire, MachineApiOkResponse, MachineApiOptions,
    MachineApiResponseEnvelope, MachineApiResponseStatus, MachineApiSchedulerResponse,
    MachineApiVersion, MachineEndpointEnvelopeSpec, MachineEndpointFieldSpec,
    MachineEndpointFieldType, MachineGoalView, MachineLocalView, MachineProofSession,
    MachineProofSnapshot, MachineRootTermSource, MachineSchedulerArtifact,
    MachineSchedulerArtifactKind, MachineSchedulerArtifactScope,
    MachineTacticOptionsConversionError, MachineTacticOptionsRequest,
    MachineValidatedEndpointEnvelope, MachineWireGrammarError, MachineWireGrammarErrorKind,
    SessionId, SnapshotId, StructuredExpr, StructuredGoal, StructuredGoalStatus,
    StructuredHypothesis, StructuredProofState, KERNEL_CHECK_PROFILE_BUILTIN_NAT_EQ_REC,
    KERNEL_CHECK_PROFILE_BUILTIN_NONE, MACHINE_API_VERSION, MACHINE_DISPLAY_PROFILE_ID,
    MACHINE_TACTIC_CANDIDATE_OUTPUT_SCHEMA,
};
pub use validation::{
    delayed_json_payload, parse_request_body, parse_request_body_with_limits,
    parse_strict_u64_token, validate_json_object, DelayedJsonPayload, FieldSpec, JsonFieldType,
    JsonPath, JsonPathElement, MachineApiErrorKind, MachineApiRequestError,
    MachineApiRequestErrorReason, ObjectSchema, StrictUnsignedIntegerError, ValidatedObject,
};
pub use verify::{
    parse_machine_verify_request, run_machine_verify_request,
    run_machine_verify_request_in_sessions, MachineCertificateWirePayload,
    MachineVerifiedModuleCertificatePayload, MachineVerifyError, MachineVerifyOkFields,
    MachineVerifyRequest, MachineVerifyResponse,
};
